name: '1 - [FEAT] Varredura de Features'
on:
    push:
        branches:
            - feature/*
jobs:
    sonar:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
                  persist-credentials: false
            - name: SonarCloud Scan
              uses: sonarsource/sonarcloud-github-action@master
              with:
                  args: >
                      -Dsonar.organization=ondlinesolutions -Dsonar.projectKey=OndlineSolutions_easycut-web
              env:
                  GITHUB_TOKEN: ${{ secrets.EASY_TOKEN }}
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    prettier:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
            uses: actions/checkout@v3
            with:
                fetch-depth: 0
                ref: ${{ github.head_ref }}
                # Make sure the value of GITHUB_TOKEN will not be persisted in repo's config
                persist-credentials: false

            - name: Prettify code
            uses: creyD/prettier_action@v4.3
            with:
                prettier_options: --write
                only_changed: True
                # Set your custom token
                github_token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

    pull-request:
        permissions: write-all
        runs-on: ubuntu-latest
        if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
        needs: [formatacao, sonar]
        steps:
            - uses: actions/checkout@v3
            - name: pull-request
              id: open-pr
              uses: docker://public.ecr.aws/y2v3z0w4/pullrequest:v1
              with:
                  github_token: ${{ secrets.PERSONAL_TOKEN }}
                  destination_branch: 'develop'
                  pr_title: 'Auto Merge Request into DEVELOP from ${{ github.ref_name }}'
                  body: '**Automated pull request**'
                  pr_label: automatic
                  get_diff: true
                  allow_no_diff: false
                  persist-credentials: false
              env:
                  GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
