name: "1 - [FEAT] Varredura de Features"
on:
    push:
        branches:
            - feature/*
jobs:
    sonar:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: SonarCloud Scan
              uses: sonarsource/sonarcloud-github-action@master
              with:
                  args: >
                      -Dsonar.organization=ondlinesolutions -Dsonar.projectKey=OndlineSolutions_easycut-web
              env:
                  GITHUB_TOKEN: ${{ secrets.EASY_TOKEN }}
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    pull-request:
        permissions: write-all
        runs-on: ubuntu-latest
        if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
        needs: [sonar]
        steps:
            - uses: actions/checkout@v3
            - name: pull-request
              id: open-pr
              uses: docker://public.ecr.aws/y2v3z0w4/pullrequest:v1
              with:
                  github_token: ${{ secrets.PERSONAL_TOKEN }}
                  destination_branch: "develop"
                  pr_title: "Auto Merge Request into DEVELOP from ${{ github.ref_name }}"
                  body: "**Automated pull request**"
                  pr_label: automatic
                  assignees: ${{ github.actor }}
                  get_diff: true
                  allow_no_diff: false
              env:
                  GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
