name: '1 - [FEAT] Varredura de Features'
on:
    push:
        branches:
            - feature/*
jobs:
    sonar:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
                  persist-credentials: false
            - name: SonarCloud Scan
              uses: sonarsource/sonarcloud-github-action@master
              with:
                  args: >
                      -Dsonar.organization=ondlinesolutions -Dsonar.projectKey=OndlineSolutions_easycut-web
              env:
                  GITHUB_TOKEN: ${{ secrets.EASY_TOKEN }}
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    format:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
            with:
            ref: ${{ github.head_ref }}
        - uses: actions/setup-node@v2
            with:
            node-version: "14.x"
        - run: npm ci
        - run: npm run format
        - name: Commit changes
            uses: stefanzweifel/git-auto-commit-action@v4
            with:
            commit_message: Apply formatting changes
            branch: ${{ github.head_ref }}

    pull-request:
        permissions: write-all
        runs-on: ubuntu-latest
        if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
        needs: [formatacao, sonar]
        steps:
            - uses: actions/checkout@v3
            - name: pull-request
              id: open-pr
              uses: docker://public.ecr.aws/y2v3z0w4/pullrequest:v1
              with:
                  github_token: ${{ secrets.PERSONAL_TOKEN }}
                  destination_branch: 'develop'
                  pr_title: 'Auto Merge Request into DEVELOP from ${{ github.ref_name }}'
                  body: '**Automated pull request**'
                  pr_label: automatic
                  get_diff: true
                  allow_no_diff: false
                  persist-credentials: false
              env:
                  GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
