name: "2 - [DEV] clean code and PR"
on:
  pull_request:
    types: [closed]
    branches: - awsdevelop
# on:
#   push:
#     branches:
#     - feature/*


jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: pull-request
    uses: OndlineSolutions/easycut-web
    with:
      destination_branch: homolog
      pr_title: "AUTOMATIC-MERGE-${{ github.ref_name }}-HOMOLOG"
      merge-method: squash
